// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payroll_Library.Models;

#nullable disable

namespace Payroll_Library.Migrations
{
    [DbContext(typeof(AriarPayrollDbContext))]
    partial class AriarPayrollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Payroll_Library.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attendance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime?>("AfternoonIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("afternoon_in");

                    b.Property<DateTime?>("AfternoonOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("afternoon_out");

                    b.Property<DateTime?>("MorningIn")
                        .HasColumnType("datetime2")
                        .HasColumnName("morning_in");

                    b.Property<DateTime?>("MorningOut")
                        .HasColumnType("datetime2")
                        .HasColumnName("morning_out");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("personal_id");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__20D6A9682236CCF9");

                    b.HasIndex("PersonalId");

                    b.ToTable("Attendance", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.Backup", b =>
                {
                    b.Property<int>("BackupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("backup_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BackupId"));

                    b.Property<DateTime>("BackupDate")
                        .HasColumnType("datetime")
                        .HasColumnName("backup_date");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date");

                    b.Property<string>("FileLocation")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("file_location");

                    b.HasKey("BackupId")
                        .HasName("PK__Backup__AE70C8808B320FD9");

                    b.ToTable("Backup", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.ContactInformation", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("contact_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("address");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("personal_id");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("phone_number");

                    b.HasKey("ContactId")
                        .HasName("PK__Contact___024E7A86D7587303");

                    b.HasIndex("PersonalId");

                    b.ToTable("Contact_Information", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.EmployeeBiometric", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("record_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<byte[]>("BiometricData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("biometric_data");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("personal_id");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("record_date");

                    b.HasKey("RecordId")
                        .HasName("PK__Employee__BFCFB4DD7DDB27F5");

                    b.HasIndex("PersonalId");

                    b.ToTable("Employee_Biometric", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.EmploymentDetail", b =>
                {
                    b.Property<int>("EmploymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmploymentId"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("hire_date");

                    b.Property<decimal>("IncomeTaxRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("income_tax_rate");

                    b.Property<decimal>("PagibigEmployeeRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("pagibig_employee_rate");

                    b.Property<decimal>("PayRate")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("pay_rate");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("personal_id");

                    b.Property<decimal>("PhilhealthEmployeeRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("philhealth_employee_rate");

                    b.Property<int>("PositionId")
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    b.Property<decimal>("SssEmployeeRate")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("sss_employee_rate");

                    b.HasKey("EmploymentId")
                        .HasName("PK__Employme__63C1606468BACA47");

                    b.HasIndex("PersonalId");

                    b.HasIndex("PositionId");

                    b.ToTable("Employment_Details", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.GrossSalary", b =>
                {
                    b.Property<int>("SalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("salary_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaryId"));

                    b.Property<decimal>("GrossSalaryAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("gross_salary_amount");

                    b.Property<Guid>("PayrollId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payroll_id");

                    b.HasKey("SalaryId")
                        .HasName("PK__Gross_Sa__A3C71C513EA2B2C1");

                    b.HasIndex("PayrollId");

                    b.ToTable("Gross_Salaries", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.Leave", b =>
                {
                    b.Property<int>("LeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leave_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeaveId"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("personal_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("LeaveId")
                        .HasName("PK__Leaves__743350BC431B4E71");

                    b.HasIndex("PersonalId");

                    b.ToTable("Leave", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.NetSalary", b =>
                {
                    b.Property<int>("NetSalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("net_salary_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NetSalaryId"));

                    b.Property<decimal>("NetSalaryAmount")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("net_salary_amount");

                    b.Property<Guid>("PayrollId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payroll_id");

                    b.HasKey("NetSalaryId")
                        .HasName("PK__Net_Sala__6C719F7AC24E5CEE");

                    b.HasIndex("PayrollId");

                    b.ToTable("Net_Salaries", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.Payroll", b =>
                {
                    b.Property<Guid>("PayrollId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payroll_id");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("personal_id");

                    b.Property<decimal>("TotalWorkDay")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("total_work_day");

                    b.HasKey("PayrollId");

                    b.HasIndex("PersonalId");

                    b.ToTable("Payroll", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.PersonalInformation", b =>
                {
                    b.Property<Guid>("PersonalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("personal_id");

                    b.Property<byte>("Age")
                        .HasColumnType("tinyint")
                        .HasColumnName("age");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date");

                    b.HasKey("PersonalId");

                    b.ToTable("Personal_Information", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("position_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("deleted_by");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("modified_by");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_date");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("position_name");

                    b.HasKey("PositionId")
                        .HasName("PK__Position__99A0E7A43CEB0EF8");

                    b.ToTable("Position", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.TotalDeduction", b =>
                {
                    b.Property<int>("TotalDeductionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total_deduction_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TotalDeductionId"));

                    b.Property<int>("IncomeTaxDeductionAmount")
                        .HasColumnType("int")
                        .HasColumnName("income_tax_deduction_amount");

                    b.Property<int>("PagibigDeductionAmount")
                        .HasColumnType("int")
                        .HasColumnName("pagibig_deduction_amount");

                    b.Property<Guid>("PayrollId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payroll_id");

                    b.Property<int>("PhilhealthDeductionAmount")
                        .HasColumnType("int")
                        .HasColumnName("philhealth_deduction_amount");

                    b.Property<int>("SssDeductionAmount")
                        .HasColumnType("int")
                        .HasColumnName("sss_deduction_amount");

                    b.HasKey("TotalDeductionId")
                        .HasName("PK__Total_De__9AF15027D43CBC2C");

                    b.HasIndex("PayrollId");

                    b.ToTable("Total_Deductions", (string)null);
                });

            modelBuilder.Entity("Payroll_Library.Models.Attendance", b =>
                {
                    b.HasOne("Payroll_Library.Models.PersonalInformation", "Personal")
                        .WithMany("Attendances")
                        .HasForeignKey("PersonalId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Personal_Information");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Payroll_Library.Models.ContactInformation", b =>
                {
                    b.HasOne("Payroll_Library.Models.PersonalInformation", "Personal")
                        .WithMany("ContactInformations")
                        .HasForeignKey("PersonalId")
                        .IsRequired()
                        .HasConstraintName("FK_Contact_Information_Personal_Information");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Payroll_Library.Models.EmployeeBiometric", b =>
                {
                    b.HasOne("Payroll_Library.Models.PersonalInformation", "Personal")
                        .WithMany("EmployeeBiometrics")
                        .HasForeignKey("PersonalId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee_Biometric_Personal_Information");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Payroll_Library.Models.EmploymentDetail", b =>
                {
                    b.HasOne("Payroll_Library.Models.PersonalInformation", "Personal")
                        .WithMany("EmploymentDetails")
                        .HasForeignKey("PersonalId")
                        .IsRequired()
                        .HasConstraintName("FK_Employment_Details_Personal_Information");

                    b.HasOne("Payroll_Library.Models.Position", "Position")
                        .WithMany("EmploymentDetails")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK_Employment_Details_Position");

                    b.Navigation("Personal");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("Payroll_Library.Models.GrossSalary", b =>
                {
                    b.HasOne("Payroll_Library.Models.Payroll", "Payroll")
                        .WithMany("GrossSalaries")
                        .HasForeignKey("PayrollId")
                        .IsRequired()
                        .HasConstraintName("FK_Gross_Salaries_Payroll");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("Payroll_Library.Models.Leave", b =>
                {
                    b.HasOne("Payroll_Library.Models.PersonalInformation", "Personal")
                        .WithMany("Leaves")
                        .HasForeignKey("PersonalId")
                        .IsRequired()
                        .HasConstraintName("FK_Leaves_Personal_Information");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Payroll_Library.Models.NetSalary", b =>
                {
                    b.HasOne("Payroll_Library.Models.Payroll", "Payroll")
                        .WithMany("NetSalaries")
                        .HasForeignKey("PayrollId")
                        .IsRequired()
                        .HasConstraintName("FK_Net_Salaries_Payroll");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("Payroll_Library.Models.Payroll", b =>
                {
                    b.HasOne("Payroll_Library.Models.PersonalInformation", "Personal")
                        .WithMany("Payrolls")
                        .HasForeignKey("PersonalId")
                        .IsRequired()
                        .HasConstraintName("FK_Payroll_Personal_Information");

                    b.Navigation("Personal");
                });

            modelBuilder.Entity("Payroll_Library.Models.TotalDeduction", b =>
                {
                    b.HasOne("Payroll_Library.Models.Payroll", "Payroll")
                        .WithMany("TotalDeductions")
                        .HasForeignKey("PayrollId")
                        .IsRequired()
                        .HasConstraintName("FK_Total_Deductions_Payroll");

                    b.Navigation("Payroll");
                });

            modelBuilder.Entity("Payroll_Library.Models.Payroll", b =>
                {
                    b.Navigation("GrossSalaries");

                    b.Navigation("NetSalaries");

                    b.Navigation("TotalDeductions");
                });

            modelBuilder.Entity("Payroll_Library.Models.PersonalInformation", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("ContactInformations");

                    b.Navigation("EmployeeBiometrics");

                    b.Navigation("EmploymentDetails");

                    b.Navigation("Leaves");

                    b.Navigation("Payrolls");
                });

            modelBuilder.Entity("Payroll_Library.Models.Position", b =>
                {
                    b.Navigation("EmploymentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
